channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=22.3.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==2.2.1
  - dataclasses==0.6
  - lz4==4.3.3
  - numpy==1.23.5
  - psutil==5.9.3
  - scikit-learn==1.5.1
  - scipy==1.10.1
  - uuid==1.30
name: mlflow-env
